export { default as HomeView } from './HomeView.vue'
export { default as LoginView } from './LoginView.vue'
export { default as ProductDetailView } from './ProductDetailView.vue'
export { default as ProfileView } from './ProfileView.vue'
export { default as RegisterView } from './RegisterView.vue'
